version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt install gettext

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install flake8 wheel

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Lint checks
          command: |
            . venv/bin/activate
            flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

      - run:
          name: Installation
          command: |
            . venv/bin/activate
            # python manage.py test
            make compile
            python setup.py install

      - store_artifacts:
          path: test-reports
          destination: test-reports
